leftnav:
- identifier: e950b852-ec24-1d82-55d6-1f4b157d38f0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: f5e54283-5c92-ef24-6a7a-d71dfd5db3a9
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 3d941cc7-6416-04a6-8e5e-580833e05484
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: 403b63df-9edb-1c7b-09a0-fefd7a3e2f17
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 40
